using System.Text.Json;
using Dapper;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace Servicedesk.Infrastructure.Audit;

/// Append-only writer + reader for <c>integration_audit</c>. No hash chain —
/// this log is operational, not tamper-evident, and the rows are mostly
/// machine-generated by background workers. Reads go through
/// <see cref="ListAsync"/>; the same instance handles both sides because the
/// surface is small enough that splitting writer + query into two services
/// would be ceremony without payoff.
public sealed class IntegrationAuditLogger : IIntegrationAuditLogger, IIntegrationAuditQuery
{
    private const string InsertSql = """
        INSERT INTO integration_audit
            (integration, event_type, outcome, endpoint, http_status, latency_ms,
             actor_id, actor_role, error_code, payload)
        VALUES
            (@Integration, @EventType, @Outcome, @Endpoint, @HttpStatus, @LatencyMs,
             @ActorId, @ActorRole, @ErrorCode, @Payload::jsonb)
        """;

    private const string SelectSql = """
        SELECT id,
               utc,
               integration,
               event_type    AS EventType,
               outcome,
               endpoint,
               http_status   AS HttpStatus,
               latency_ms    AS LatencyMs,
               actor_id      AS ActorId,
               actor_role    AS ActorRole,
               error_code    AS ErrorCode,
               payload::text AS PayloadJson
          FROM integration_audit
        """;

    private readonly NpgsqlDataSource _dataSource;
    private readonly ILogger<IntegrationAuditLogger> _logger;

    public IntegrationAuditLogger(NpgsqlDataSource dataSource, ILogger<IntegrationAuditLogger> logger)
    {
        _dataSource = dataSource;
        _logger = logger;
    }

    public async Task LogAsync(IntegrationAuditEvent evt, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(evt);
        if (string.IsNullOrWhiteSpace(evt.Integration))
            throw new ArgumentException("Integration is required.", nameof(evt));
        if (string.IsNullOrWhiteSpace(evt.EventType))
            throw new ArgumentException("EventType is required.", nameof(evt));

        var payloadJson = evt.Payload is null
            ? "{}"
            : JsonSerializer.Serialize(evt.Payload);

        try
        {
            await using var connection = await _dataSource.OpenConnectionAsync(cancellationToken);
            await connection.ExecuteAsync(new CommandDefinition(InsertSql, new
            {
                evt.Integration,
                evt.EventType,
                Outcome = evt.Outcome.ToString().ToLowerInvariant(),
                evt.Endpoint,
                evt.HttpStatus,
                evt.LatencyMs,
                evt.ActorId,
                evt.ActorRole,
                evt.ErrorCode,
                Payload = payloadJson,
            }, cancellationToken: cancellationToken));
        }
        catch (Exception ex)
        {
            // Never let an integration-audit write failure cascade into the
            // caller's primary work (e.g. a token refresh succeeding but
            // logging failing must not surface as "refresh failed"). Log
            // and swallow — the row is gone, but the integration is fine.
            _logger.LogError(ex, "integration_audit insert failed for {Integration}/{EventType}",
                evt.Integration, evt.EventType);
        }
    }

    public async Task<IntegrationAuditPage> ListAsync(
        string integration,
        long? cursorId,
        int limit,
        CancellationToken cancellationToken = default)
    {
        var clamped = Math.Clamp(limit, 1, 200);
        var sql = SelectSql + " WHERE integration = @Integration";
        var parameters = new DynamicParameters();
        parameters.Add("Integration", integration);
        if (cursorId is not null)
        {
            sql += " AND id < @CursorId";
            parameters.Add("CursorId", cursorId.Value);
        }
        sql += " ORDER BY id DESC LIMIT @Limit";
        parameters.Add("Limit", clamped + 1);

        await using var connection = await _dataSource.OpenConnectionAsync(cancellationToken);
        var rows = (await connection.QueryAsync<IntegrationAuditEntry>(
            new CommandDefinition(sql, parameters, cancellationToken: cancellationToken))).ToList();

        long? nextCursor = null;
        if (rows.Count > clamped)
        {
            nextCursor = rows[clamped - 1].Id;
            rows = rows.Take(clamped).ToList();
        }
        return new IntegrationAuditPage(rows, nextCursor);
    }
}

public interface IIntegrationAuditQuery
{
    Task<IntegrationAuditPage> ListAsync(
        string integration,
        long? cursorId,
        int limit,
        CancellationToken cancellationToken = default);
}
